[master]: Merged to branches/ dev to the master

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,3 +1,6 @@
+# If you want to look the log files,
+# Mean , run the command
+# >> docker inspect --format='{{.LogPath}}' <container_name_or_id> (in your  console/cmd )
 services:
     # =====================
     # PostgreSQL Database
@@ -7,7 +10,7 @@ services:
         image: postgres
         env_file: ./.env
         environment:
-            - POSTGRES_USER=${POSTGRES_DB_USER}
+            - POSTGRES_USER=${POSTGRES_USER}
             - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
             - POSTGRES_DB=${POSTGRES_DB}
         healthcheck:
@@ -19,21 +22,30 @@ services:
         ports:
             - "5432:5432"
         networks:
-            - backend
-        volumes:
-            - postgres_data:/var/lib/postgresql/18/data
+            backend:
+                aliases:
+                    - db
+                    - postgres
         logging:
             driver: "json-file"
             options:
                 max-size: "10m"
                 max-file: "3"
+        deploy:
+            resources:
+                limits:
+                    memory: 400M
+                    cpus: "0.5"
+                reservations:
+                    cpus: "0.2"
+                    memory: 150M
     # =====================
     # FastAPI Application
     # =====================
-    backend:
+    api:
         container_name: ${COMPOSE_PROJECT_NAME:-fastapi}_static
         healthcheck:
-            test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/" ]
+            test: [ "CMD", "curl", "-f", "http://0.0.0.0:8003/health" ]
             interval: 30s
             timeout: 10s
             retries: 3
@@ -42,22 +54,88 @@ services:
             context: .
         env_file: ./.env
         environment:
-            DATABASE_HOST: db
-            DATABASE_PORT: 5432
-            REDIS_HOST: redis
-            REDIS_PORT: 6380
+            POSTGRES_USER: ${POSTGRES_USER}
+            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
+            POSTGRES_DB: ${POSTGRES_DB}
+            DATABASE_HOST: ${POSTGRES_HOST}
+            DATABASE_PORT: ${POSTGRES_PORT}
+            REDIS_HOST: 'redis'
+            REDIS_PORT: 6379
+            PYTHONPATH: /www/src
+            WEB_CONCURRENCY: 2
         volumes:
-            - ./:/app
-            - static_volume:/www/src/cryptomarket
-            - medis_volume:/www/src/media
+            - ./:/www/src
+            - volume_static:/www/src/collectstatic
+            - volume_media:/www/src/media
         command:
             - bash
             - -c
             - |
+                set -e
+                echo "Waiting for database..."
+
+                MAX_RETRIES=30
+                RETRY_COUNT=0
+
+                until python -c "
+                import psycopg2
+                import os
+                import sys
+                try:
+                    conn = psycopg2.connect(
+                    host=os.environ['DATABASE_HOST'],
+                    user=os.environ['POSTGRES_USER'],
+                    password=os.environ.get('POSTGRES_PASSWORD'),
+                    dbname=os.environ.get('POSTGRES_DB')
+                    )
+                    conn.close()
+                    sys.exit(0)
+                except Exception as e:
+                    print(f'Connection failed: { e }')
+                    sys.exit(1)
+                "; do
+                            RETRY_COUNT=$((RETRY_COUNT + 1))
+                            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+                                echo "Docker-file: Failed to connect to PostgreSQL after $MAX_RETRIES attempts"
+                                exit 1
+                            fi
+                            echo "Docker-file: Waiting for PostgreSQL... attempt $RETRY_COUNT/$MAX_RETRIES"
+                            sleep 2
+                        done
+        
+                        echo "Docker-file: PostgreSQL is ready!"
+                        echo "Creating schema 'crypto' if not exists..."
+                                                   
+                python -c "
+                import psycopg2
+                import os
+                conn = psycopg2.connect(
+                host=os.environ['DATABASE_HOST'],
+                user=os.environ.get('POSTGRES_USER'),
+                password=os.environ.get('POSTGRES_PASSWORD'),
+                dbname=os.environ.get('POSTGRES_DB')
+                )
+                conn.autocommit = True
+                cur = conn.cursor()
+                cur.execute('CREATE SCHEMA IF NOT EXISTS crypto')
+                cur.close()
+                conn.close()
+                print('Docker-file: Schema crypto created')
+                "
+                
+                echo "Running migrations..."
+                alembic downgrade base
                 alembic upgrade head
-                uvicorn main:app --host 0.0.0.0 --port 8003 --reload
+                echo "Starting application..."
+                python -m cryptomarket.main
+
+#                alembic downgrade base
+#                rm alembic/versions/*.py
+#                alembic revision --autogenerate
+#                alembic upgrade head
+#                python -m cryptomarket.main
         ports:
-            - "${API_PORT:-8000}:8000"
+            - "8003:8003"
         depends_on:
             db:
                 condition: service_healthy
@@ -65,12 +143,23 @@ services:
                 condition: service_healthy
         restart: unless-stopped
         networks:
-            - backend
+            backend:
+                aliases:
+                  - api
+                  - backend
         logging:
             driver: "json-file"
             options:
                 max-size: "10m"
                 max-file: "3"
+        deploy:
+            resources:
+                limits:
+                    memory: 512M
+                    cpus: "0.5"
+                reservations:
+                    memory: 512M
+                    cpus: "0.2"
     # =====================
     # Celery Worker
     # =====================
@@ -80,11 +169,13 @@ services:
             context: .
             dockerfile: ./Dockerfile  # Тот же Dockerfile, что и для backend
         env_file: ./.env
+        environment:
+            CELERY_BROKER_URL: redis://redis:6379/0
+            CELERY_RESULT_BACKEND: redis://redis:6379/0
         command:
             - sh
             - -c
-            - "celery -A project.celery worker --loglevel=info"
-
+            - "celery -A cryptomarket.project.celery_ worker --loglevel=info --concurrency=1"
         volumes:
             - .:/www/src
         depends_on:
@@ -92,8 +183,8 @@ services:
                 condition: service_healthy
             redis:
                 condition: service_healthy
-            backend:
-                condition: service_started
+            api:
+                condition: service_healthy
         restart: unless-stopped
         networks:
             - backend
@@ -102,6 +193,14 @@ services:
             options:
                 max-size: "10m"
                 max-file: "3"
+        deploy:
+            resources:
+                limits:
+                    memory: 400M
+                    cpus: "0.5"
+                reservations:
+                    memory: 256M
+                    cpus: "0.2"
     # =====================
     # Celery Beat (Scheduler)
     # =====================
@@ -111,10 +210,13 @@ services:
             context: .
             dockerfile: ./Dockerfile
         env_file: ./.env
+        environment:
+            CELERY_BROKER_URL: redis://redis:6379/0
+            CELERY_RESULT_BACKEND: redis://redis:6379/0
         command:
             - sh
             - -c
-            - "celery -A project.celery beat --loglevel=info"
+            - "celery -A cryptomarket.project.celery_ beat --loglevel=info"
         volumes:
             - .:/www/src
         depends_on:
@@ -124,34 +226,45 @@ services:
                 condition: service_healthy
             celery_worker:
                 condition: service_started
+        networks:
+            - backend
         restart: unless-stopped
+        deploy:
+            resources:
+                limits:
+                    memory: 400M
+                    cpus: "0.5"
+                reservations:
+                    memory: 256M
+                    cpus: "0.2"
     # =====================
     # Flower (Celery Monitoring)
     # =====================
-    flower:
-        container_name: ${COMPOSE_PROJECT_NAME:-fastapi}_flower
-        image: mher/flower
-        env_file: .env
-        environment:
-            CELERY_BROKER_URL: redis://:${REDIS_PASSWORD:-}@redis:6380/0
-            CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD:-}@redis:6380/0
-            FLOWER_PORT: 5555
-            FLOWER_BASIC_AUTH: ${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
-        ports:
-            - "${FLOWER_PORT:-5555}:5555"
-        depends_on:
-            redis:
-                condition: service_healthy
-            celery_worker:
-                condition: service_started
-        restart: unless-stopped
-        networks:
-            - backend
-        logging:
-            driver: "json-file"
-            options:
-                max-size: "10m"
-                max-file: "3"
+#    flower:
+#        container_name: ${COMPOSE_PROJECT_NAME:-fastapi}_flower
+#        image: mher/flower
+#        env_file: .env
+#        environment:
+#            REDIS_PORT: 6379
+#            CELERY_BROKER_URL: redis://redis:6379/0
+#            CELERY_RESULT_BACKEND: redis://redis:6379/0
+#            FLOWER_PORT: 5555
+#            FLOWER_BASIC_AUTH: ${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
+#        ports:
+#            - "${FLOWER_PORT:-5555}:5555"
+#        depends_on:
+#            redis:
+#                condition: service_healthy
+#            celery_worker:
+#                condition: service_started
+#        restart: unless-stopped
+#        networks:
+#            - backend
+#        logging:
+#            driver: "json-file"
+#            options:
+#                max-size: "10m"
+#                max-file: "3"
     # =====================
     # Nginx (Reverse Proxy)
     # =====================
@@ -163,33 +276,43 @@ services:
         depends_on:
             api:
                 condition: service_healthy
-            backend:
-                condition: service_started
             db:
                 condition: service_healthy
         volumes:
             - volume_static:/www/src/collectstatic
+            - volume_media:/www/src/media
         restart: on-failure
         ports:
             - "80:80"
         networks:
-            - backend
-    adminer:
-        container_name: ${COMPOSE_PROJECT_NAME:-fastapi}_adminer
-        image: adminer:4.8.1
-        ports:
-            - "${ADMINER_PORT:-8080}:8080"
-        depends_on:
-            db:
-                condition: service_healthy
-        restart: unless-stopped
-        networks:
-            - backend
-        logging:
-            driver: "json-file"
-            options:
-                max-size: "10m"
-                max-file: "3"
+            backend:
+                aliases:
+                    - nginx
+                    - proxiserver
+        deploy:
+            resources:
+                limits:
+                    memory: 400M
+                    cpus: "0.5"
+                reservations:
+                    memory: 256M
+                    cpus: "0.2"
+#    adminer:
+#        container_name: ${COMPOSE_PROJECT_NAME:-fastapi}_adminer
+#        image: adminer:4.8.1
+#        ports:
+#            - "${ADMINER_PORT:-8080}:8080"
+#        depends_on:
+#            db:
+#                condition: service_healthy
+#        restart: unless-stopped
+#        networks:
+#            - backend
+#        logging:
+#            driver: "json-file"
+#            options:
+#                max-size: "10m"
+#                max-file: "3"
     # =====================
     # Redis Cache
     # =====================
@@ -204,20 +327,29 @@ services:
 
         command: redis-server --bind 0.0.0.0
         volumes:
-            - redis_data:${COMPOSE_PROJECT_NAME:-fastapi}_redis_data
+            - redis_data:/data
         ports:
-            - "6380:6380"
+            - "6380:6379"
+        networks:
+            backend:
+                aliases:
+                    - radis
+                    - cache
+        deploy:
+            resources:
+                limits:
+                    memory: 512M
+                    cpus: "0.5"
+                reservations:
+                    memory: 256M
+                    cpus: "0.2"
+        restart: unless-stopped
+
 volumes:
-    postgres_data:
-        name: /var/lib/postgresql/18/data
     redis_data:
-        name: ${COMPOSE_PROJECT_NAME:-fastapi}_redis_data
-    static_volume:
-        name: www/src/cryptomarket
-    medis_volume:
-        name: www/src/media
+    volume_static:
+    volume_media:
 
 networks:
   backend:
-    name: ${COMPOSE_PROJECT_NAME:-fastapi}_backend
     driver: bridge
